### ISSUE TITLE
LU translations

### ISSUE THREAD

**Issue by alainvalain** [joho1968/POMjs#2]
POM_cfgTitle = 'Zoufallspasswuertgenerator';
POM_cfgSlogan = 'Keng Cookien, <span style="display:inline-block">keng Trackeren.</span><br/>Nemme Passwierder.';
POM_cfgGenPasswordHint = 'Passwuert genereieren';

**Comment by joho1968** [comment]
Thank you 😊 Could you look at #1 and see if you can translate the other (HTML) block too?

**Comment by alainvalain** [comment]
<meta name="description" content=“Zoufallspasswuertgenerator" lang=“lb">
    <title lang=“lb">POMjs - Zoufallspasswuertgenerator</title>

**Comment by joho1968** [comment]
Added to 1.1.2, thank you @alainvalain :blush:
