### ISSUE TITLE
FR translations

### ISSUE THREAD

**Issue by alainvalain** [joho1968/POMjs#3]
POM_cfgTitle = 'Générateur de mot de passe au hazard';
POM_cfgSlogan = 'Pas de cookies, <span style="display:inline-block">pas de traceurs.</span><br/>Juste des mots de passe.';
POM_cfgGenPasswordHint = 'Générer mot de passe';

**Comment by joho1968** [comment]
Thank you 😊 Could you look at #1 and see if you can translate the other (HTML) block too?

**Comment by alainvalain** [comment]
<meta name="description" content=“Générateur de mot de passe au hazard" lang=“fr">
    <title lang=“fr">POMjs - Générateur de mot de passe au hazard</title>

**Comment by joho1968** [comment]
Added to 1.1.2, thank you @alainvalain :blush:
