### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by gregorgodler** [joho1968/POMjs#6]
I can add Slovenian translation.

**Comment by joho1968** [comment]
That would be great! You can just post the translated strings in this issue and I'll incorporate them into the distribution.

**Comment by gregorgodler** [comment]
I think these are all translations that are needed.

index.html:
`<meta name="description" content="Generator Naključnih Gesel" lang="sl">`
`<title lang="sl">POMjs - Generator Naključnih Gesel</title>`

password-om.js:
`/* Add your translation here */`
`case 'sl':`
`            POM_cfgTitle = 'Generator Naključnih Gesel';`
`            POM_cfgSlogan = 'Brez piškotkov, <span style="display:inline-block">nič sledilnikov.</span><br/>Samo geslo.';`
`            POM_cfgGenPasswordHint = 'Generiraj geslo';`
`            break;`

**Comment by joho1968** [comment]
Thank you for your contribution! :blush: 1.1.4 has now been released and includes your Slovenian translation :+1:
